environments:
  dev:
    catalog: "pharmacy_dev"
    schema: "pbm"
    contract_status: "draft"

  qa:
    catalog: "pharmacy_qa"
    schema: "pbm"
    contract_status: "proposed"

  prod:
    catalog: "pharmacy_prod"
    schema: "pbm"
    contract_status: "active"
