environments:
  dev:
    catalog: "scripius_dev"
    schema: "pbm"
    contract_status: "draft"

  qa:
    catalog: "scripius_qa"
    schema: "pbm"
    contract_status: "proposed"

  prod:
    catalog: "scripius_prod"
    schema: "pbm"
    contract_status: "active"
