environments:
  dev:
    catalog: "ih_genie_governance2_dev"
    schema: "scripius"
    contract_status: "draft"

  qa:
    catalog: "ih_genie_governance2_qa"
    schema: "scripius"
    contract_status: "proposed"

  prod:
    catalog: "ih_genie_governance2"
    schema: "scripius"
    contract_status: "active"
